version: '3'

services:
  # app:
  #   build: .
  #   entrypoint: ./.docker/entrypoint.sh
  #   container_name: auth-api-app
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app
  #   depends_on:
  #     - db
  #   extra_hosts:
  #     - "host.docker.internal:172.17.0.1"

  db:
    image: mongo:4.4.4
    container_name: auth-api-mongodb
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}

  mongo-express:
    image: mongo-express
    restart: always
    container_name: auth-api-mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
    depends_on:
      - db
