version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: auth-api-app
    hostname: docker
    ports:
      - ${PORT}:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    image: mongo:4.4.4
    container_name: auth-api-mongodb
    hostname: docker
    restart: always
    ports:
      - ${DATABASE_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}

  mongo-express:
    image: mongo-express
    restart: always
    container_name: auth-api-mongo-express
    hostname: docker
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${DATABASE_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${DATABASE_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DATABASE_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
